### ISSUE TITLE
Server incorrectly handles disconnects due to incorrect password

### ISSUE THREAD

**Issue by mollybeam** [Wizxrd/SRC#6]
After the client sends the TryDisconnect callback after an incorrect password is given, the server appears to send a single export frame before allowing the connection to timeout. 
![image](https://github.com/user-attachments/assets/9be1d7a1-6702-49d8-aabb-85962c238227)
(rest of conversation truncated, but it's just the rest of the export JSON object)
![image](https://github.com/user-attachments/assets/04d93ca8-e1ca-48a0-be32-c4344699d6fb)
After the client issues a FIN,ACK the server does not close the connection and continues to send data.

**Comment by Wizxrd** [comment]
this has been fixed and will be in the next update.
